In [1]:
import pandas as pd

In [36]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [21]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [37]:
df = df.drop(columns=['Parental_Involvement',
       'Access_to_Resources', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home'], axis=1)

In [38]:
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
0,23,84,No,7,73,Male,67
1,19,64,No,8,59,Female,61
2,24,98,Yes,7,91,Male,74
3,29,89,Yes,8,98,Male,71
4,19,92,Yes,6,65,Female,70

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Extracurricular_Activities  6607 non-null   object
 3   Sleep_Hours                 6607 non-null   int64
 4   Previous_Scores             6607 non-null   int64
 5   Gender                      6607 non-null   object
 6   Exam_Score                  6607 non-null   int64
dtypes: int64(5), object(2)
memory usage: 361.4+ KB

In [39]:
df.describe()

       Hours_Studied   Attendance  Sleep_Hours  Previous_Scores   Exam_Score
count    6607.000000  6607.000000   6607.00000      6607.000000  6607.000000
mean       19.975329    79.977448      7.02906        75.070531    67.235659
std         5.990594    11.547475      1.46812        14.399784     3.890456
min         1.000000    60.000000      4.00000        50.000000    55.000000
25%        16.000000    70.000000      6.00000        63.000000    65.000000
50%        20.000000    80.000000      7.00000        75.000000    67.000000
75%        24.000000    90.000000      8.00000        88.000000    69.000000
max        44.000000   100.000000     10.00000       100.000000   101.000000

In [40]:
df[df["Exam_Score"] == 101]

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
1525,27,98,Yes,6,93,Female,101

In [41]:
df = df[df["Exam_Score"] <= 100]

In [42]:
df[df["Exam_Score"] == 101]

Empty DataFrame
Columns: [Hours_Studied, Attendance, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Gender, Exam_Score]
Index: []

In [43]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [44]:
df["Extracurricular_Activities"] = le.fit_transform(df["Extracurricular_Activities"])
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
0,23,84,0,7,73,Male,67
1,19,64,0,8,59,Female,61
2,24,98,1,7,91,Male,74
3,29,89,1,8,98,Male,71
4,19,92,1,6,65,Female,70

In [45]:
df["Gender"] = le.fit_transform(df["Gender"])
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
0,23,84,0,7,73,1,67
1,19,64,0,8,59,0,61
2,24,98,1,7,91,1,74
3,29,89,1,8,98,1,71
4,19,92,1,6,65,0,70

In [46]:
df["Exam_Score"] = (df["Exam_Score"] >= 68).astype(int)
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
0,23,84,0,7,73,1,0
1,19,64,0,8,59,0,0
2,24,98,1,7,91,1,1
3,29,89,1,8,98,1,1
4,19,92,1,6,65,0,1

In [47]:
df["Exam_Score"].value_counts()

Exam_Score
0    3599
1    3007
Name: count, dtype: int64

In [48]:
df.describe()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Gender,Exam_Score
count,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000
mean,19.974266,79.974720,0.595973,7.029216,75.067817,0.577354,0.455192
std,5.990424,11.546219,0.490740,1.468177,14.399184,0.494018,0.498026
min,1.000000,60.000000,0.000000,4.000000,50.000000,0.000000,0.000000
25%,16.000000,70.000000,0.000000,6.000000,63.000000,0.000000,0.000000
50%,20.000000,80.000000,1.000000,7.000000,75.000000,1.000000,0.000000
75%,24.000000,90.000000,1.000000,8.000000,88.000000,1.000000,1.000000
max,44.000000,100.000000,1.000000,10.000000,100.000000,1.000000,1.000000