In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Video Games Sales (1980-2024) - Raw.csv")
df.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,17-09-2013,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,18-11-2014,03-01-2018
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,28-10-2002,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,17-09-2013,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,06-11-2015,14-01-2018

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [4]:
df.shape

(64016, 14)

In [5]:
df.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [6]:
df = df.drop(columns=['img', 'publisher', 'developer',
       'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'], axis=1)

In [7]:
df.head()

                         title console    genre  critic_score  total_sales
0           Grand Theft Auto V     PS3   Action           9.4        20.32
1           Grand Theft Auto V     PS4   Action           9.7        19.39
2  Grand Theft Auto: Vice City     PS2   Action           9.6        16.15
3           Grand Theft Auto V    X360   Action           NaN        15.86
4    Call of Duty: Black Ops 3     PS4  Shooter           8.1        15.09

In [8]:
df["title"].unique()

array(['Grand Theft Auto V', 'Grand Theft Auto: Vice City',
       'Call of Duty: Black Ops 3', ..., 'Yoru, Tomosu',
       'Yunohana SpRING! ~Mellow Times~',
       'Yurukill: The Calumniation Games'], shape=(39798,), dtype=object)

In [9]:
df.shape

(64016, 5)

In [10]:
df = df.dropna(subset=['critic_score'])

In [11]:
df.shape

(6678, 5)

In [12]:
df = df.drop_duplicates(subset='title')

In [13]:
df.shape

(4718, 5)

In [14]:
df.head()

                            title console    genre  critic_score  total_sales
0              Grand Theft Auto V     PS3   Action           9.4        20.32
2     Grand Theft Auto: Vice City     PS2   Action           9.6        16.15
4       Call of Duty: Black Ops 3     PS4  Shooter           8.1        15.09
5  Call of Duty: Modern Warfare 3    X360  Shooter           8.7        14.82
6         Call of Duty: Black Ops    X360  Shooter           8.8        14.74

In [15]:
df = pd.get_dummies(df, columns=['genre', 'console'])

In [16]:
df.describe()

       critic_score  total_sales
count   4718.000000  2876.000000
mean       7.178741     0.745876
std        1.488640     1.447265
min        1.000000     0.000000
25%        6.400000     0.110000
50%        7.500000     0.290000
75%        8.200000     0.720000
max       10.000000    20.320000

In [17]:
df = df.drop(columns=["title"], axis=1)
df.head()

,critic_score,total_sales,genre_Action,genre_Action-Adventure,genre_Adventure,genre_Board Game,genre_Education,genre_Fighting,genre_MMO,genre_Misc,...,console_VC,console_WW,console_Wii,console_WiiU,console_X360,console_XB,console_XBL,console_XOne,console_XS,console_iOS
0,9.4,20.32,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,9.6,16.15,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,8.1,15.09,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,8.7,14.82,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
6,8.8,14.74,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [18]:
df.shape

(4718, 58)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4718 entries, 0 to 63999
Data columns (total 58 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   critic_score            4718 non-null   float64
 1   total_sales             2876 non-null   float64
 2   genre_Action            4718 non-null   bool
 3   genre_Action-Adventure  4718 non-null   bool
 4   genre_Adventure         4718 non-null   bool
 5   genre_Board Game        4718 non-null   bool
 6   genre_Education         4718 non-null   bool
 7   genre_Fighting          4718 non-null   bool
 8   genre_MMO               4718 non-null   bool
 9   genre_Misc              4718 non-null   bool
 10  genre_Music             4718 non-null   bool
 11  genre_Party             4718 non-null   bool
 12  genre_Platform          4718 non-null   bool
 13  genre_Puzzle            4718 non-null   bool
 14  genre_Racing            4718 non-null   bool
 15  genre_Role-Playing      4718 non-null   bool
 16  genre_Shooter           4718 non-null   bool
 17  genre_Simulation        4718 non-null   bool
 18  genre_Sports            4718 non-null   bool
 19  genre_Strategy          4718 non-null   bool
 20  genre_Visual Novel      4718 non-null   bool
 21  console_3DS             4718 non-null   bool
 22  console_AJ              4718 non-null   bool
 23  console_All             4718 non-null   bool
 24  console_DC              4718 non-null   bool
 25  console_DS              4718 non-null   bool
 26  console_DSiW            4718 non-null   bool
 27  console_GB              4718 non-null   bool
 28  console_GBA             4718 non-null   bool
 29  console_GBC             4718 non-null   bool
 30  console_GC              4718 non-null   bool
 31  console_GEN             4718 non-null   bool
 32  console_N64             4718 non-null   bool
 33  console_NES             4718 non-null   bool
 34  console_NGage           4718 non-null   bool
 35  console_NS              4718 non-null   bool
 36  console_PC              4718 non-null   bool
 37  console_PS              4718 non-null   bool
 38  console_PS2             4718 non-null   bool
 39  console_PS3             4718 non-null   bool
 40  console_PS4             4718 non-null   bool
 41  console_PS5             4718 non-null   bool
 42  console_PSN             4718 non-null   bool
 43  console_PSP             4718 non-null   bool
 44  console_PSV             4718 non-null   bool
 45  console_SAT             4718 non-null   bool
 46  console_SCD             4718 non-null   bool
 47  console_SNES            4718 non-null   bool
 48  console_VC              4718 non-null   bool
 49  console_WW              4718 non-null   bool
 50  console_Wii             4718 non-null   bool
 51  console_WiiU            4718 non-null   bool
 52  console_X360            4718 non-null   bool
 53  console_XB              4718 non-null   bool
 54  console_XBL             4718 non-null   bool
 55  console_XOne            4718 non-null   bool
 56  console_XS              4718 non-null   bool
 57  console_iOS             4718 non-null   bool
dtypes: bool(56), float64(2)
memory usage: 368.6 KB

In [20]:
df['total_sales'] = df['total_sales'].fillna(df['total_sales'].median())

In [21]:
X = df.drop(columns=["critic_score"], axis=1)
y = df["critic_score"]

In [22]:
X.shape

(4718, 57)

In [23]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

In [24]:
X_pca.shape

(4718, 2)

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.3)

In [27]:
df.corr(numeric_only=True)

,critic_score,total_sales,genre_Action,genre_Action-Adventure,genre_Adventure,genre_Board Game,genre_Education,genre_Fighting,genre_MMO,genre_Misc,...,console_VC,console_WW,console_Wii,console_WiiU,console_X360,console_XB,console_XBL,console_XOne,console_XS,console_iOS
critic_score,1.000000,0.187974,-0.116540,0.033120,0.018511,-0.018378,0.008033,0.024800,0.024123,-0.067119,...,0.029414,-0.028668,-0.061451,-0.015827,-0.007023,0.049897,-0.015205,0.035181,0.008033,0.008780
total_sales,0.187974,1.000000,0.035451,0.031881,-0.031188,-0.003388,-0.000606,-0.010677,-0.009678,-0.003332,...,-0.025777,-0.030255,0.006791,-0.020826,0.146881,0.009340,-0.054493,0.013174,-0.003514,-0.007861
genre_Action,-0.116540,0.035451,1.000000,-0.051919,-0.102102,-0.005831,-0.005831,-0.094723,-0.016503,-0.095719,...,-0.022848,-0.035272,0.023169,0.008007,0.021859,0.040229,-0.011048,0.000903,-0.005831,-0.013043
genre_Action-Adventure,0.033120,0.031881,-0.051919,1.000000,-0.033058,-0.001888,-0.001888,-0.030669,-0.005343,-0.030992,...,-0.013282,-0.016254,-0.024257,0.094320,-0.013261,0.003732,-0.013212,0.091214,-0.001888,-0.004223
genre_Adventure,0.018511,-0.031188,-0.102102,-0.033058,1.000000,-0.003712,-0.003712,-0.060313,-0.010508,-0.060947,...,-0.008655,0.039767,0.034520,-0.019443,-0.031891,-0.016662,-0.035931,-0.017049,-0.003712,-0.008305
genre_Board Game,-0.018378,-0.003388,-0.005831,-0.001888,-0.003712,1.000000,-0.000212,-0.003444,-0.000600,-0.003480,...,-0.001492,-0.001825,-0.003538,-0.001581,-0.004260,-0.001461,-0.003243,-0.000974,-0.000212,-0.000474
genre_Education,0.008033,-0.000606,-0.005831,-0.001888,-0.003712,-0.000212,1.000000,-0.003444,-0.000600,-0.003480,...,-0.001492,-0.001825,-0.003538,-0.001581,0.049767,-0.001461,-0.003243,-0.000974,-0.000212,-0.000474
genre_Fighting,0.024800,-0.010677,-0.094723,-0.030669,-0.060313,-0.003444,-0.003444,1.000000,-0.009749,-0.056542,...,-0.005567,-0.021988,-0.012108,0.000755,-0.006010,0.023910,-0.021475,-0.015817,-0.003444,-0.007705
genre_MMO,0.024123,-0.009678,-0.016503,-0.005343,-0.010508,-0.000600,-0.000600,-0.009749,1.000000,-0.009851,...,-0.004222,-0.005167,-0.010014,-0.004476,-0.012058,-0.004134,-0.009180,-0.002756,-0.000600,-0.001342
genre_Misc,-0.067119,-0.003332,-0.095719,-0.030992,-0.060947,-0.003480,-0.003480,-0.056542,-0.009851,1.000000,...,-0.005995,0.030793,0.093095,0.000239,0.013544,-0.023977,0.004184,-0.015983,-0.003480,-0.007786
genre_Music,0.030680,0.003338,-0.024781,-0.008024,-0.015779,-0.000901,-0.000901,-0.014639,-0.002550,-0.014793,...,-0.006340,-0.007758,0.014935,-0.006721,0.007409,-0.006208,-0.013784,0.047510,-0.000901,-0.002016
genre_Party,-0.044217,-0.011406,-0.022615,-0.007322,-0.014400,-0.000822,-0.000822,-0.013359,-0.002328,-0.013499,...,-0.005786,-0.007080,0.002689,0.204323,-0.002552,-0.005665,-0.012579,-0.003776,-0.000822,-0.001839
genre_Platform,0.036351,-0.032322,-0.119365,-0.038648,-0.076003,-0.004340,-0.004340,-0.070510,-0.012285,-0.071251,...,0.091655,0.025362,0.001818,0.025331,-0.072845,-0.006512,0.013874,-0.008300,-0.004340,-0.009709
genre_Puzzle,0.002298,-0.056924,-0.094723,-0.030669,-0.060313,-0.003444,-0.003444,-0.055953,-0.009749,-0.056542,...,0.003766,0.070006,-0.024481,-0.016875,-0.058673,-0.023728,0.094452,-0.015817,-0.003444,0.050456
genre_Racing,-0.012925,0.021730,-0.111594,-0.036132,-0.071055,-0.004058,-0.004058,-0.065920,-0.011485,-0.066613,...,-0.020464,0.011550,-0.024840,-0.007358,0.015791,0.013312,-0.019584,0.055244,0.052247,-0.009077
genre_Role-Playing,0.076404,-0.053460,-0.164187,-0.053160,-0.104542,-0.005970,-0.005970,-0.096987,-0.016898,-0.098006,...,0.011603,-0.046508,-0.057509,-0.027652,-0.039294,-0.010726,-0.040104,-0.018344,-0.005970,0.023763
genre_Shooter,0.003376,0.076588,-0.149477,-0.048398,-0.095176,-0.005435,-0.005435,-0.088298,-0.015384,-0.089226,...,0.000047,-0.004863,-0.023021,-0.016432,0.121238,0.021184,0.102822,0.013914,-0.005435,0.007725
genre_Simulation,-0.033841,-0.001212,-0.082253,-0.026632,-0.052373,-0.002991,-0.002991,-0.048588,-0.008465,-0.049098,...,0.000173,0.000390,0.025091,-0.012289,-0.012210,-0.009775,-0.030547,-0.013734,-0.002991,-0.006690
genre_Sports,0.009868,0.081091,-0.121879,-0.039462,-0.077604,-0.004432,-0.004432,-0.071995,-0.012544,-0.072752,...,-0.023674,-0.019661,0.052078,0.002389,0.060593,-0.007545,-0.046278,-0.020351,-0.004432,-0.009913
genre_Strategy,0.037104,-0.068184,-0.109457,-0.035440,-0.069695,-0.003980,-0.003980,-0.064657,-0.011265,-0.065337,...,-0.011562,0.006245,-0.048252,-0.021922,-0.045956,-0.019027,-0.001976,-0.005758,-0.003980,-0.008903
genre_Visual Novel,0.018280,-0.007295,-0.008246,-0.002670,-0.005251,-0.000300,-0.000300,-0.004871,-0.000849,-0.004922,...,-0.002110,-0.002582,-0.005004,-0.002237,-0.006025,-0.002066,-0.004587,-0.001377,-0.000300,-0.000671
console_3DS,-0.007768,-0.046597,0.002382,0.056035,0.004313,-0.003039,-0.003039,-0.011536,-0.008603,0.001652,...,-0.021385,-0.026169,-0.050719,-0.022671,-0.061072,-0.020939,-0.046495,-0.013958,-0.003039,-0.006799
console_AJ,-0.031094,-0.003514,-0.005831,-0.001888,-0.003712,-0.000212,-0.000212,-0.003444,-0.000600,-0.003480,...,-0.001492,-0.001825,-0.003538,-0.001581,-0.004260,-0.001461,-0.003243,-0.000974,-0.000212,-0.000474
console_All,0.028656,-0.004970,-0.008246,-0.002670,-0.005251,-0.000300,-0.000300,0.041094,-0.000849,-0.004922,...,-0.002110,-0.002582,-0.005004,-0.002237,-0.006025,-0.002066,-0.004587,-0.001377,-0.000300,-0.000671
console_DC,-0.030559,-0.051450,0.003335,-0.027914,0.013950,-0.003135,-0.003135,0.068635,-0.008873,-0.005905,...,-0.022056,-0.026990,-0.052310,-0.023382,-0.062988,-0.021596,-0.047954,-0.014396,-0.003135,-0.007012
console_DS,0.009968,-0.018167,-0.043816,-0.030927,0.052937,-0.003473,-0.003473,-0.039655,-0.009831,0.009435,...,-0.024437,-0.029904,-0.057957,-0.025906,-0.069788,-0.023928,-0.053130,-0.015950,-0.003473,-0.007769
console_DSiW,-0.049905,-0.022597,-0.011024,-0.012139,-0.014334,-0.001363,-0.001363,-0.022147,-0.003859,0.038217,...,-0.009592,-0.011738,-0.022749,-0.010168,-0.027393,-0.009392,-0.020854,-0.006260,-0.001363,-0.003050
console_GB,0.026984,-0.011651,-0.004857,-0.008024,0.012942,-0.000901,-0.000901,-0.014639,-0.002550,0.000413,...,-0.006340,-0.007758,-0.015036,-0.006721,-0.018106,-0.006208,-0.013784,-0.004138,-0.000901,-0.002016
console_GBA,-0.113977,-0.078503,0.058667,-0.035902,0.005128,-0.004032,-0.004032,-0.006637,-0.011412,0.003061,...,-0.028367,-0.034714,-0.067280,-0.030073,-0.081014,-0.027776,-0.061677,-0.018515,-0.004032,-0.009019
console_GBC,0.042042,0.010243,-0.013043,-0.004223,0.073325,-0.000474,-0.000474,-0.007705,-0.001342,0.021024,...,-0.003337,-0.004083,-0.007914,-0.003537,-0.009529,-0.003267,-0.007255,-0.002178,-0.000474,-0.001061
console_GC,-0.046713,-0.060134,-0.005473,-0.029418,0.015997,-0.003304,-0.003304,0.029640,-0.009351,0.032644,...,-0.023244,-0.028444,-0.055129,-0.024642,-0.066383,-0.022760,-0.050538,-0.015171,-0.003304,-0.007390
console_GEN,0.025215,-0.006818,-0.010101,-0.003270,-0.006432,-0.000367,-0.000367,-0.005967,-0.001040,-0.006029,...,-0.002584,-0.003162,-0.006129,-0.002739,-0.007380,-0.002530,-0.005618,-0.001687,-0.000367,-0.000822
console_N64,0.009231,-0.026415,0.017427,-0.017875,-0.008977,-0.002007,-0.002007,-0.004637,-0.005682,-0.019097,...,-0.014123,-0.017283,-0.033497,-0.014973,-0.040335,-0.013829,-0.030707,-0.009218,-0.002007,-0.004490
console_NES,0.032851,0.014090,-0.013043,-0.004223,0.018905,-0.000474,-0.000474,0.021376,-0.001342,-0.007786,...,-0.003337,-0.004083,-0.007914,-0.003537,-0.009529,-0.003267,-0.007255,-0.002178,-0.000474,-0.001061
console_NGage,-0.034492,-0.018648,-0.014948,-0.010018,-0.019701,-0.001125,-0.001125,0.006360,-0.003184,-0.006265,...,-0.007916,-0.009686,-0.018774,-0.008392,-0.022606,-0.007751,-0.017210,-0.005166,-0.001125,-0.002517
console_NS,0.048977,-0.041812,0.023030,0.075525,-0.012194,0.091306,-0.002322,0.023122,-0.006572,-0.007979,...,-0.016336,-0.019991,-0.038745,-0.017319,-0.046654,-0.015996,-0.035518,-0.010663,-0.002322,-0.005194
console_PC,0.084534,-0.084328,-0.102627,-0.026120,0.026764,-0.005267,-0.005267,-0.073742,0.065611,-0.054240,...,-0.037060,-0.045352,-0.087898,-0.039289,-0.105840,-0.036288,-0.080577,-0.024189,-0.005267,-0.011783
console_PS,0.004406,0.023520,-0.026836,-0.030798,0.014242,-0.003459,-0.003459,0.040594,-0.009790,-0.010923,...,-0.024335,-0.029779,-0.057716,-0.025798,-0.069497,-0.023828,-0.052909,-0.015883,-0.003459,-0.007737
console_PS2,0.064952,0.122443,0.014831,-0.021596,-0.004985,-0.003914,-0.003914,0.000565,0.009468,-0.038089,...,-0.027541,-0.033702,-0.065319,-0.029197,-0.078653,-0.026967,-0.059879,-0.017976,-0.003914,-0.008756
console_PS3,0.019707,0.101600,0.087156,0.019288,-0.017592,-0.003861,-0.003861,0.051835,0.009863,-0.006640,...,-0.027167,-0.033245,-0.064434,-0.028801,-0.077587,-0.026601,-0.059067,-0.017732,-0.003861,-0.008638
console_PS4,0.061819,0.193728,0.003882,0.221889,-0.015877,-0.002451,-0.002451,-0.034037,0.024534,-0.028783,...,-0.017244,-0.021102,-0.040899,-0.018281,-0.049248,-0.016885,-0.037493,-0.011255,-0.002451,-0.005483
console_PS5,0.004620,-0.009303,0.000521,-0.004998,-0.009828,-0.000561,-0.000561,0.015464,-0.001589,-0.009214,...,-0.003949,-0.004832,-0.009366,-0.004186,-0.011278,-0.003867,-0.008586,-0.002577,-0.000561,-0.001256
console_PSN,0.004523,-0.040554,0.010540,-0.003825,-0.014625,-0.002593,-0.002593,-0.003746,-0.007339,-0.015408,...,-0.018242,-0.022323,-0.043265,-0.019339,-0.052097,-0.017862,-0.039662,-0.011906,-0.002593,-0.005800
console_PSP,-0.052965,-0.032285,-0.006558,-0.034738,-0.032899,-0.003901,-0.003901,0.019892,-0.011042,0.025951,...,-0.027448,-0.033588,-0.065099,-0.029098,-0.078387,-0.026876,-0.059677,-0.017915,-0.003901,-0.008727
console_PSV,-0.018687,0.004805,0.000521,-0.004998,-0.009828,-0.000561,-0.000561,0.015464,-0.001589,0.015140,...,-0.003949,-0.004832,-0.009366,-0.004186,-0.011278,-0.003867,-0.008586,-0.002577,-0.000561,-0.001256
console_SAT,0.031409,-0.011846,-0.010554,-0.007073,-0.013910,-0.000794,-0.000794,0.056677,-0.002248,-0.013040,...,-0.005589,-0.006839,-0.013255,-0.005925,-0.015961,-0.005472,-0.012151,-0.003648,-0.000794,-0.001777
console_SCD,0.001778,-0.007861,0.005833,-0.004223,-0.008305,-0.000474,-0.000474,-0.007705,-0.001342,-0.007786,...,-0.003337,-0.004083,-0.007914,-0.003537,-0.009529,-0.003267,-0.007255,-0.002178,-0.000474,-0.001061
console_SNES,0.059268,-0.017076,-0.011367,-0.009271,0.006658,-0.001041,-0.001041,0.009686,-0.002947,-0.017092,...,-0.007325,-0.008964,-0.017374,-0.007766,-0.020920,-0.007173,-0.015927,-0.004781,-0.001041,-0.002329
console_VC,0.029414,-0.025777,-0.022848,-0.013282,-0.008655,-0.001492,-0.001492,-0.005567,-0.004222,-0.005995,...,1.000000,-0.012843,-0.024891,-0.011126,-0.029972,-0.010276,-0.022818,-0.006850,-0.001492,-0.003337
console_WW,-0.028668,-0.030255,-0.035272,-0.016254,0.039767,-0.001825,-0.001825,-0.021988,-0.005167,0.030793,...,-0.012843,1.000000,-0.030459,-0.013615,-0.036677,-0.012575,-0.027923,-0.008382,-0.001825,-0.004083
console_Wii,-0.061451,0.006791,0.023169,-0.024257,0.034520,-0.003538,-0.003538,-0.012108,-0.010014,0.093095,...,-0.024891,-0.030459,1.000000,-0.026388,-0.071085,-0.024372,-0.054118,-0.016246,-0.003538,-0.007914
console_WiiU,-0.015827,-0.020826,0.008007,0.094320,-0.019443,-0.001581,-0.001581,0.000755,-0.004476,0.000239,...,-0.011126,-0.013615,-0.026388,1.000000,-0.031774,-0.010894,-0.024190,-0.007262,-0.001581,-0.003537
console_X360,-0.007023,0.146881,0.021859,-0.013261,-0.031891,-0.004260,0.049767,-0.006010,-0.012058,0.013544,...,-0.029972,-0.036677,-0.071085,-0.031774,1.000000,-0.029347,-0.065165,-0.019563,-0.004260,-0.009529
console_XB,0.049897,0.009340,0.040229,0.003732,-0.016662,-0.001461,-0.001461,0.023910,-0.004134,-0.023977,...,-0.010276,-0.012575,-0.024372,-0.010894,-0.029347,1.000000,-0.022342,-0.006707,-0.001461,-0.003267
console_XBL,-0.015205,-0.054493,-0.011048,-0.013212,-0.035931,-0.003243,-0.003243,-0.021475,-0.009180,0.004184,...,-0.022818,-0.027923,-0.054118,-0.024190,-0.065165,-0.022342,1.000000,-0.014893,-0.003243,-0.007255
console_XOne,0.035181,0.013174,0.000903,0.091214,-0.017049,-0.000974,-0.000974,-0.015817,-0.002756,-0.015983,...,-0.006850,-0.008382,-0.016246,-0.007262,-0.019563,-0.006707,-0.014893,1.000000,-0.000974,-0.002178
console_XS,0.008033,-0.003514,-0.005831,-0.001888,-0.003712,-0.000212,-0.000212,-0.003444,-0.000600,-0.003480,...,-0.001492,-0.001825,-0.003538,-0.001581,-0.004260,-0.001461,-0.003243,-0.000974,1.000000,-0.000474
console_iOS,0.008780,-0.007861,-0.013043,-0.004223,-0.008305,-0.000474,-0.000474,-0.007705,-0.001342,-0.007786,...,-0.003337,-0.004083,-0.007914,-0.003537,-0.009529,-0.003267,-0.007255,-0.002178,-0.000474,1.000000

In [33]:
from sklearn.ensemble import RandomForestRegressor

model1 = RandomForestRegressor()
model1.fit(X_train, y_train)

RandomForestRegressor()

In [34]:
model2 = RandomForestRegressor()
model2.fit(X_train_pca, y_train_pca)

RandomForestRegressor()

In [35]:
from sklearn.metrics import r2_score

In [36]:
pred1 = model1.predict(X_test)

r2_score(y_test, pred1)

0.024928596840598227

In [37]:
pred2 = model2.predict(X_test_pca)

r2_score(y_test_pca, pred2)

0.018014202197479512

#### Dataset is too weak for simple ML due to very less correlation