In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV

In [2]:
digits = load_digits()

In [3]:
X = digits.data
y = digits.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
svc_model = SVC(kernel='rbf', C=1)
svc_model.fit(X_train, y_train)
svc_model.score(X_test, y_test)

0.9861111111111112

In [7]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
},
cv=5,
return_train_score=True
)
clf.fit(X_train, y_train)
clf.cv_results_

{'mean_fit_time': array([0.01726518, 0.09956679, 0.01514735, 0.09421802, 0.01665349,
        0.09306264]),
 'std_fit_time': array([0.00162634, 0.00571495, 0.00065249, 0.0021088 , 0.00096527,
        0.00835165]),
 'mean_score_time': array([0.00355959, 0.02899141, 0.00300589, 0.02502117, 0.00366302,
        0.02535405]),
 'std_score_time': array([0.0005245 , 0.00196459, 0.00019346, 0.00032411, 0.00076456,
        0.00021217]),
 'param_C': masked_array(data=[0.1, 0.1, 1, 1, 10, 10],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.1, 'kernel': 'linear'},
  {'C': 0.1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'}],
 'split0_test_score': array([0.97569444, 0.10763889, 0.97569444, 0.4375    , 0.97569444,
        0.48611111]),
 'split1_test_score': array([0.97222222, 0.10763889, 0.97222222, 0.40625   , 0.97222222,
        0.47916667]),
 'split2_test_score': array([0.96515679, 0.10801394, 0.96515679, 0.45644599, 0.96515679,
        0.50174216]),
 'split3_test_score': array([0.9825784 , 0.10801394, 0.9825784 , 0.48432056, 0.9825784 ,
        0.54355401]),
 'split4_test_score': array([0.95818815, 0.10452962, 0.95818815, 0.44599303, 0.95818815,
        0.47735192]),
 'mean_test_score': array([0.970768  , 0.10716705, 0.970768  , 0.44610192, 0.970768  ,
        0.49758517]),
 'std_test_score': array([0.00843337, 0.00132934, 0.00843337, 0.02541592, 0.00843337,
        0.02453852]),
 'rank_test_score': array([1, 6, 1, 5, 1, 4]),
 'split0_train_score': array([1.        , 0.10704961, 1.        , 1.        , 1.        ,
        1.        ]),
 'split1_train_score': array([1.        , 0.10704961, 1.        , 1.        , 1.        ,
        1.        ]),
 'split2_train_score': array([1.        , 0.10695652, 1.        , 1.        , 1.        ,
        1.        ]),
 'split3_train_score': array([1.        , 0.10695652, 1.        , 1.        , 1.        ,
        1.        ]),
 'split4_train_score': array([1.        , 0.10782609, 1.        , 1.        , 1.        ,
        1.        ]),
 'mean_train_score': array([1.        , 0.10716767, 1.        , 1.        , 1.        ,
        1.        ]),
 'std_train_score': array([0.        , 0.00033183, 0.        , 0.        , 0.        ,
        0.        ])}

In [8]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.017265,0.001626,0.003560,0.000525,0.1,linear,"{'C': 0.1, 'kernel': 'linear'}",0.975694,0.972222,0.965157,...,0.970768,0.008433,1,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
1,0.099567,0.005715,0.028991,0.001965,0.1,rbf,"{'C': 0.1, 'kernel': 'rbf'}",0.107639,0.107639,0.108014,...,0.107167,0.001329,6,0.10705,0.10705,0.106957,0.106957,0.107826,0.107168,0.000332
2,0.015147,0.000652,0.003006,0.000193,1,linear,"{'C': 1, 'kernel': 'linear'}",0.975694,0.972222,0.965157,...,0.970768,0.008433,1,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
3,0.094218,0.002109,0.025021,0.000324,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.437500,0.406250,0.456446,...,0.446102,0.025416,5,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
4,0.016653,0.000965,0.003663,0.000765,10,linear,"{'C': 10, 'kernel': 'linear'}",0.975694,0.972222,0.965157,...,0.970768,0.008433,1,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
5,0.093063,0.008352,0.025354,0.000212,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.486111,0.479167,0.501742,...,0.497585,0.024539,4,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000

In [9]:
df[['param_C', 'param_kernel', 'mean_test_score']]

  param_C param_kernel  mean_test_score
0     0.1       linear         0.970768
1     0.1          rbf         0.107167
2       1       linear         0.970768
3       1          rbf         0.446102
4      10       linear         0.970768
5      10          rbf         0.497585

In [10]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [11]:
clf.best_params_, clf.best_score_

({'C': 0.1, 'kernel': 'linear'}, 0.9707680023228804)

In [12]:
randomized_clf = RandomizedSearchCV(SVC(), {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
}, 
cv=5,
n_iter=2)

randomized_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=2,
                   param_distributions={'C': [0.1, 1, 10],
                                        'kernel': ['linear', 'rbf']})

In [13]:
randomized_clf.best_params_, randomized_clf.best_score_

({'kernel': 'rbf', 'C': 10}, 0.9916545683313978)

In [14]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [0.1,1,10],
            'kernel': ['rbf','linear', 'poly', 'sigmoid']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,10,30]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    },
    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params': {}
    },
    'naive_bayes_multinomial': {
        'model': MultinomialNB(),
        'params': {}
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy'],
            
        }
    }     
}

In [15]:
scores = []

for model_name, mp in model_params.items():
    clf =  RandomizedSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False, n_iter=3)
    clf.fit(digits.data, digits.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 1 is smaller than n_iter=3. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 2 is smaller than n_iter=3. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

                     model  best_score                  best_params
0                      svm    0.968842  {'kernel': 'poly', 'C': 10}
1            random_forest    0.926577         {'n_estimators': 30}
2      logistic_regression    0.922114                     {'C': 1}
3     naive_bayes_gaussian    0.806928                           {}
4  naive_bayes_multinomial    0.870350                           {}
5            decision_tree    0.810814     {'criterion': 'entropy'}

In [ ]:
# best model will be svm with 96.88% score.